// src/seed/seed.controller.ts
import { Controller, Post } from '@nestjs/common'
import { PrismaService } from '../prisma/prisma.service'

@Controller('seed')
export class SeedController {
  constructor(private prisma: PrismaService) {}

  @Post()
  async seed() {
    await this.prisma.product.createMany({
      data: [
        {
          id: '6b6f2f80-d29a-4d32-b229-070b56712b01',
          productId: 'P001',
          name: 'Carpigiani LB 502 G TR',
          category: 'Machine',
          unit: 'Unit',
          price: 350000,
          minStock: 1,
          quantity: 2,
          description: 'Professional gelato batch freezer imported from Italy.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '9f8cefc2-3bfc-4709-a768-9adf3947f3d9',
          productId: 'P002',
          name: 'Bravo Trittico Startronic Plus',
          category: 'Machine',
          unit: 'Unit',
          price: 420000,
          minStock: 1,
          quantity: 1,
          description: 'All-in-one pasteurizer and batch freezer.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'e52e0c3c-c499-45e3-bc49-d1cf405c8bb1',
          productId: 'P003',
          name: 'Frigomat GX2',
          category: 'Machine',
          unit: 'Unit',
          price: 280000,
          minStock: 1,
          quantity: 2,
          description: 'Tabletop ice cream machine for gelato shops.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'ceec295e-8102-46e2-a093-e326eb509b69',
          productId: 'P004',
          name: 'Fresh Milk',
          category: 'Ingredient',
          unit: 'Kilogram',
          price: 2.5,
          minStock: 10,
          quantity: 50,
          description: 'High-quality fresh milk used in gelato base.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'b7ef1f87-f0d0-47d7-9757-9d902a92e204',
          productId: 'P005',
          name: 'Cream 35%',
          category: 'Ingredient',
          unit: 'Kilogram',
          price: 3.2,
          minStock: 5,
          quantity: 20,
          description: 'Full-fat cream for rich gelato texture.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '7ac36f3d-34a4-4ed9-83f2-79d2c00b32f5',
          productId: 'P006',
          name: 'Skimmed Milk Powder',
          category: 'Ingredient',
          unit: 'Kilogram',
          price: 2.0,
          minStock: 5,
          quantity: 25,
          description: 'Used to stabilize gelato mixture.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'f37019b2-7ab2-4b6f-b332-dc2b826c8483',
          productId: 'P007',
          name: 'Vanilla Paste',
          category: 'Flavoring',
          unit: 'Bottle',
          price: 25.0,
          minStock: 2,
          quantity: 10,
          description: 'High-grade Madagascar vanilla paste.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'a967e354-b8aa-4de4-a7aa-49627e006776',
          productId: 'P008',
          name: 'Pistachio Puree',
          category: 'Flavoring',
          unit: 'Kilogram',
          price: 35.0,
          minStock: 2,
          quantity: 5,
          description: 'Premium pistachio paste from Bronte, Italy.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '7d04fc6e-530f-4b53-a69a-015616dfe007',
          productId: 'P009',
          name: 'Hazelnut Paste',
          category: 'Flavoring',
          unit: 'Kilogram',
          price: 28.0,
          minStock: 2,
          quantity: 6,
          description: '100% pure hazelnut paste from Piemonte.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'eaa027b3-5e89-407a-bb7e-3e93c799fbfb',
          productId: 'P010',
          name: '500ml Takeaway Cup',
          category: 'Packaging',
          unit: 'Box',
          price: 8.0,
          minStock: 5,
          quantity: 30,
          description: 'Plastic takeaway cups for gelato (box of 100).',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'e1ba9e44-4b4e-4c61-bb56-4c56e4f464cc',
          productId: 'P011',
          name: 'Spoon Set',
          category: 'Packaging',
          unit: 'Pack',
          price: 3.0,
          minStock: 5,
          quantity: 20,
          description: 'Disposable gelato spoons (pack of 100).',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'b4f40c7e-bf1d-4d02-8400-9f8dfcf2ae93',
          productId: 'P012',
          name: 'Napkins',
          category: 'Packaging',
          unit: 'Box',
          price: 5.0,
          minStock: 3,
          quantity: 10,
          description: 'Tissue napkins for customers (box of 500).',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'de758c4b-1745-47df-b519-0ab3f28901b4',
          productId: 'P013',
          name: 'Gelato Spatula',
          category: 'Utensil',
          unit: 'Piece',
          price: 4.5,
          minStock: 5,
          quantity: 15,
          description: 'Flexible spatula for gelato scooping.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '1a86f947-5d52-4a4a-aaf9-c4f27391f471',
          productId: 'P014',
          name: 'Mixing Bowl',
          category: 'Utensil',
          unit: 'Piece',
          price: 12.0,
          minStock: 3,
          quantity: 10,
          description: 'Stainless steel bowl used in preparation.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '25f14aeb-1b42-498b-b07a-d5c295398ec4',
          productId: 'P015',
          name: 'Measuring Jug',
          category: 'Utensil',
          unit: 'Piece',
          price: 6.0,
          minStock: 3,
          quantity: 8,
          description: '1L measuring jug with ml markings.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '6a74c22c-7038-4c7b-b6b4-0b4db85a36a8',
          productId: 'P016',
          name: 'Basic Gelato Recipe',
          category: 'Instruction',
          unit: 'Copy',
          price: 5.0,
          minStock: 0,
          quantity: 100,
          description: 'Instruction manual for making vanilla gelato.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '3b6e8aa3-5383-40e6-9211-3ff7a032469c',
          productId: 'P017',
          name: 'Pistachio Gelato Recipe',
          category: 'Instruction',
          unit: 'Copy',
          price: 5.0,
          minStock: 0,
          quantity: 100,
          description: 'Step-by-step guide for pistachio gelato.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '9e8e52e0-f826-4e3c-872e-59bc09a261cb',
          productId: 'P018',
          name: 'Hazelnut Gelato Recipe',
          category: 'Instruction',
          unit: 'Copy',
          price: 5.0,
          minStock: 0,
          quantity: 100,
          description: 'Hazelnut gelato recipe used in training.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'fe77061a-6c7a-42b0-bf6f-d62a2b6885ef',
          productId: 'P019',
          name: 'Batch Pasteurizer 60L',
          category: 'Machine',
          unit: 'Unit',
          price: 500000,
          minStock: 1,
          quantity: 1,
          description: 'Large capacity pasteurizer for gelato base.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: '28bc82f7-ec7a-4f1f-b89c-89eaed3e1d33',
          productId: 'P020',
          name: 'Cold Storage Freezer',
          category: 'Machine',
          unit: 'Unit',
          price: 200000,
          minStock: 1,
          quantity: 2,
          description: 'Used to store gelato at -20°C.',
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      skipDuplicates: true, // กันการ insert ซ้ำ
    })

    return { message: '✅ Seeded Product data successfully.' }
  }
}
