version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tinntinn
      POSTGRES_PASSWORD: Fr33domlife
      POSTGRES_DB: inventory-pro
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
